--General
require("plugins")
require("keys")
require("settings")

-- Plugins
require("config.nv-compe")
require("config.nv-bufferline")
require("config.nv-lualine")
require("config.nv-autopairs")
require("config.nv-colorizer")
require("config.nv-telescope")
require("config.nv-treesitter")
require("config.nv-nvimtree")
require("config.nv-ls")
require("config.nv-lspconfig")
require("config.nv-trouble")
require("config.nv-completion")
require("config.nv-comment")
require("config.nv-whichkey")
